version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: gratefultolord/foodgram_backend
    restart: always
    volumes:
      - static_volume:/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env
    container_name: foodgram_backend

  frontend:
    image: gratefultolord/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
    container_name: foodgram_nginx
